<?php

namespace FlexibleShippingUspsVendor\Octolize\Brand\UpsellingBox;

use FlexibleShippingUspsVendor\WPDesk\ShowDecision\WooCommerce\ShippingMethodInstanceStrategy;
class ShippingMethodInstanceShouldShowStrategy extends ShippingMethodInstanceStrategy
{
}
